### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [lucian-ilie/E-MEM#1]
Hi,
as explained in private mail it would help if you would consider tagging releases.  This would help automatic tools in Debian detecting new versions to be distributed to Debian users as soon as possible.
Thanks for considering, Andreas.

**Comment by nkhiste** [comment]
Thanks for the suggestion. I just added a release tag for E-MEM.

**Comment by tillea** [comment]
On Wed, May 10, 2017 at 05:43:39AM -0700, Nilesh Vinod Khiste wrote:
> Thanks for the suggestion. I just added a release tag for E-MEM.
Thanks, version 1.0.0 uploaded to Debian.  Andreas.
